handle = "Sara"
port = [5100, 5101]         # UDP/TCP Ports > 1024
whoisport = 4000            # Discovery-Port für WHO, JOIN, LEAVE
autoreply = "Ich bin gerade abwesend"
imagepath = "~/chat_images"
broadcast_ip = "10.129.170.255"  # automatisch ermittelt
debug = true